import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/sessionwrapper";
import LayoutWrapper from "./components/layoutwrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "OpenHands",
   icons: {
    icon: '/vercel.svg', // This is the path to your logo in /public
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} -z-20 antialiased bg-black`}
      >
          <SessionWrapper>
            <LayoutWrapper>
              {children}
              {/* <Footer/> */}
            </LayoutWrapper>
          </SessionWrapper>
      </body>
    </html>
  );
}
